package entities;
// Generated 2016/06/17 10:09:56 by Hibernate Tools 3.6.0.Final
/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Department department;
	private String name;
	private String nameYomikata;;
	private String email;
	private String telephone;
	private String address;

	public Member() {
	}

	public Member(Integer id, String name, String nameYomikata) {
		this.id = id;
		this.name = name;
		this.nameYomikata = nameYomikata;
	}

	public Member(Integer id, Department department, String name, String nameYomikata, String email,
			String telephone, String address) {
		this.id = id;
		this.department = department;
		this.name = name;
		this.nameYomikata = nameYomikata;
		this.email = email;
		this.telephone = telephone;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameYomikata() {
		return this.nameYomikata;
	}

	public void setNameYomikata(String nameYomikata) {
		this.nameYomikata = nameYomikata;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
